name: "Integração Contínua - Client - SAM"
on:
  pull_request:
    branches:
        - "main"
        - "release"
        - "development"

jobs:
  sam-validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Configure AWS credentials
        id: creds
        uses: aws-actions/configure-aws-credentials@v1
        with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
            aws-region: ${{ secrets.AWS_REGION }}
      - name: "Injeta o ambiente"
        run: sed -i "s/{{ENVIRONMENT}}/ci/g" ./client/template.yaml
      - name: "Executa o SAM Validate"
        run: sam validate --template-file ./client/template.yaml
  
  sam-build:
    runs-on: ubuntu-latest
    needs: [sam-validate]
    steps:
      - uses: actions/checkout@v2
      - name: Configure AWS credentials
        id: creds
        uses: aws-actions/configure-aws-credentials@v1
        with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
            aws-region: ${{ secrets.AWS_REGION }}
      - name: "Injeta o ambiente"
        run: sed -i "s/{{ENVIRONMENT}}/ci/g" ./client/template.yaml
      - name: "Executa o SAM Validate"
        run: sam build --template-file ./client/template.yaml
